### PR TITLE
Inject a navbar web component

### PR DESCRIPTION
**Pull request by halkeye**
image

Based on the webcomponent framework i've been working on this week
https://github.com/halkeye/jenkins-io-components
https://halkeye.github.io/jenkins-io-components/

Leaving it as a draft as i merged my navbar early. All the links are relative when they should be absolute, but otherwise it works.

### CODE REVIEW

**Comment by halkeye** [comment]
Its probably mergable once https://github.com/halkeye/jenkins-io-components/pull/4 is merged, though there's still more polish that needs to be done.

**Comment by halkeye** [comment]
> <script data="jio" src="https://unpkg.com/@halkeye/jenkins-io-components?module" type="module"></script>
> <script data="jio" nomodule="" src="https://unpkg.com/@halkeye/jenkins-io-components"></script>

So this always uses the latest version of my component. I don't know if thats desirable, but i don't think building a new image all the time is good either.

**Comment by halkeye** [comment]
image

The footer looks nice. Not sure wiki content is considered Creative commons license though.

**Review by lemeurherve — APPROVED** [review]

**Comment by halkeye** [comment]
Lets wait till @wadeck decides about the web components stuff, then I can do another PR later for a footer too.

**Review by dduportal — APPROVED** [review]

**Review by Wadeck — APPROVED** [review]
I imagine that you plan to move your library to the jenkins-infra organization? :) (I don't want to make this a blocker for this PR but that should be done at some point)

I quickly check the repo, there is nothing triggering my spider sense => 👍

**Comment by lemeurherve** [comment]
> I imagine that you plan to move your library to the jenkins-infra organization? :) (I don't want to make this a blocker for this PR but that should be done at some point)

@Wadeck FTR it's now done: https://github.com/jenkins-infra/helpdesk/issues/3250

**Pull request merged**
